version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: yii2-super-simple-scheduling-system-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mysql
  mysql:
    image: percona/percona-server
    container_name: yii2-super-simple-scheduling-system-mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./data/db/mysql:/var/lib/mysql"