version: '2'
services:
  web:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: yii2-super-simple-scheduling-system-nginx
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html/"
    ports:
      - "8011:80"
    command: "nginx -g 'daemon off;'"
    depends_on:
      - mysql
      - php
      - react-front-hook

  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: yii2-super-simple-scheduling-system-php
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"

  mysql:
    image: percona/percona-server
    container_name: yii2-super-simple-scheduling-system-mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./docker/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./docker/mysql/data/db/mysql:/var/lib/mysql"

  react-front-hook:
    container_name: yii2-super-simple-scheduling-system-node
    build:
      context: ./docker/node/
      dockerfile: Dockerfile
    volumes:
      - './react-front-hook/:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development